name: Add a Community Theme
description: Submit a theme to be included on the Themes page
title: 'THEME:'
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Quick Checklist
        Thank you for sharing your themes with the Astro community! Please fill out this form as completely as possible.

        ✅ Source code for the theme is available in a public repository
        ✅ All NPM dependencies used in the theme are public
        ✅ Theme preview image or screenshot included (see below for details)

        Optional: Though not required, live demos are a great way to show off all your hard work!
  - type: input
    attributes:
      label: Theme title
    validations:
      required: true
  - type: textarea
    attributes:
      label: Short description and preview image
      description: Preview images should be 16:9 aspect ratio, 906px wide or larger.
    validations:
      required: true
  - type: input
    attributes:
      label: Public repository URL
      placeholder: https://github.com/username/repo
    validations:
      required: true
  - type: input
    attributes:
      label: Live demo URL
      placeholder: https://portfolio-demo.netlify.app
