blank_issues_enabled: true
contact_links:
  - name: Add your Website to the Showcase
    url: https://astro.build/showcase/submit
    about: Submit or update a website to be included on the Showcase page
  - name: Add a Community Theme
    url: https://astro.build/themes/submit
    about: Submit or update a theme to be included on the Themes page
