name: Setup Node.js & pnpm
description: Setup Node.js and pnpm and install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3

    - name: Setup Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 18
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --prod
