name: Format main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/format.yml@main
    with:
      command: "format"
    secrets: inherit
