name: Worker Build Logs

on:
  push:
    branches: ["**"]

jobs:
  build-logs:
    if: github.repository == 'withastro/astro.build'
    name: Cloudflare Worker Build
    runs-on: ubuntu-latest
    steps:
      - name: Stream Workers Builds Logs
        uses: withastro/workers-builds-log-action@v1
        with:
          api-token: ${{ secrets.CF_BUILDS_API_TOKEN }}
          account-id: ${{ secrets.CF_ACCOUNT_ID }}
          worker-tag: ${{ secrets.CF_WORKER_TAG }}
